version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: twothree-postgres
    environment:
      POSTGRES_DB: twothree_db
      POSTGRES_USER: twothree_user
      POSTGRES_PASSWORD: twothree_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/src/main/resources/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - twothree-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: twothree-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@twothree.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - twothree-network

  redis:
    image: redis:7-alpine
    container_name: twothree-redis
    ports:
      - "6379:6379"
    networks:
      - twothree-network

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: twothree-redis-commander
    environment:
      REDIS_HOSTS: local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis
    networks:
      - twothree-network

  adminer:
    image: adminer:latest
    container_name: twothree-adminer
    ports:
      - "8082:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    depends_on:
      - postgres
    networks:
      - twothree-network

volumes:
  postgres_data:

networks:
  twothree-network:
    driver: bridge 