version: '3.8'

services:
  # INT Environment (Development/Testing)
  twothree-backend-int:
    build: .
    container_name: twothree-backend-int
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=int
      - PORT=8080
      - DATABASE_URL=jdbc:postgresql://postgres-int:5432/twothree_int
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=password
    depends_on:
      - postgres-int
    profiles:
      - int
    restart: unless-stopped

  # PostgreSQL for INT
  postgres-int:
    image: postgres:15
    container_name: postgres-int
    environment:
      - POSTGRES_DB=twothree_int
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_int_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    profiles:
      - int
    restart: unless-stopped

  # PROD Environment
  twothree-backend-prod:
    build: .
    container_name: twothree-backend-prod
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - PORT=8080
      - DATABASE_URL=jdbc:postgresql://postgres-prod:5432/twothree
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=password
      - JWT_SECRET_KEY=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    depends_on:
      - postgres-prod
    profiles:
      - prod
    restart: unless-stopped

  # PostgreSQL for PROD
  postgres-prod:
    image: postgres:15
    container_name: postgres-prod
    environment:
      - POSTGRES_DB=twothree
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    profiles:
      - prod
    restart: unless-stopped

volumes:
  postgres_data:
  postgres_int_data: 