targets:
  $default:
    builders:
      json_serializable:
        options:
          # Options configure how `json_serializable` will generate code.
          explicit_to_json: true
          include_if_null: false 